image: python:3.5

before_script:
  - python -V        # Print out python version for debugging

test:
  script:
  - pip install tox
  - tox

run:
  script:
  - python setup.py bdist_wheel
  # an alternative approach is to install and run:
  - pip install dist/*
  # run the command here
  artifacts:
    paths:
    - dist/*.whl
