image: python:3.5

before_script:
  - python -V        # Print out python version for debugging

test:
  script:
  - pip install tox
  - tox

run:
  variables:
    NAME: pynogram

  script:
  - python setup.py sdist bdist_wheel --universal

  # docs and LICENSE should be in sources
  - tar -tf dist/*.tar.gz | grep -v "/$NAME" | grep '/LICENSE'
  - tar -tf dist/*.tar.gz | grep -v "/$NAME" | grep '/docs/.\+md'

  # to install and run:
  - pip install -U dist/*.whl
  - time $NAME -b winter
  # only two files should left
  - pip show -f $NAME | grep '^ ' | grep -v " $NAME[-/]"

  artifacts:
    paths:
    - dist/*.whl
