# use the default image as
# the python images contain too old PyPy version in their repos
# image: python:3.5

before_script:
  - apt-get update -qq
  - apt-get install -y -qq git  # for .fix.sh script
  - apt-get install -y -qq python python-pip python-dev
  - apt-get install -y -qq python3 python3-pip python3-dev
  - apt-get update -qq && apt-get install -y -qq pypy pypy-dev
  - python -V        # Print out python versions for debugging
  - python3 -V
  - pypy -V

test:
  script:
  - pip install tox
  - tox

run:
  variables:
    NAME: pynogram
    # https://stackoverflow.com/a/35101311/1177288
    PYTHONIOENCODING: utf-8

  script:
  - python setup.py sdist bdist_wheel --universal

  # docs and LICENSE should be in sources
  - tar -tf dist/*.tar.gz | grep -v "/$NAME" | grep '/LICENSE'
  - tar -tf dist/*.tar.gz | grep -v "/$NAME" | grep '/docs/.\+md'

  # to install and run:
  - pip install -U dist/*.whl
  - time $NAME -b winter -v
  - time $NAME --pbn 4089 --draw-final -vv
  # only two files should left
  - pip show -f $NAME | grep '^ ' | grep -v " $NAME[-/]" |
    wc -l | exit $(awk '{print $1-2}')

  artifacts:
    paths:
    - dist/*.whl
